version: '3'
services:
  backend:
    image: saick5/tabsy1.1:latest
    ports:
      - "5001:5000"
    restart: always
    networks:
      - tabsy-network
  backend2:
    image: saick5/tabsy1.1:latest
    ports:
      - "5002:5000"
    restart: always
    networks:
      - tabsy-network
# Define a custom bridge network
networks:
  tabsy-network:
    driver: bridge